name: Publish release on tag

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build-wasm:
    name: WASM (Custom Marian) Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: 2.0.9
          # actions-cache-folder: emsdk-cache

      - name: Verify Emscripten setup
        run: emcc -v

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure builds
        run: |
          mkdir -p build-wasm
          cd build-wasm
          emcmake cmake -DCOMPILE_WASM=on ../bergamot-translator

      - name: Compile
        working-directory: build-wasm
        run: emmake make -j2

      - name: Instantiate simd wormhole
        working-directory: build-wasm
        run: bash ../bergamot-translator/wasm/patch-artifacts-enable-wormhole.sh

      - name: Import GEMM library from a separate wasm module
        working-directory: build-wasm
        run: bash ../bergamot-translator/wasm/patch-artifacts-import-gemm-module.sh

      - name: Upload wasm artifact
        uses: actions/upload-artifact@v2
        with:
          name: bergamot-translator-worker
          path: ${{github.workspace}}/build-wasm/bergamot-translator-worker.*

  build-extension:
    runs-on: ubuntu-latest
    needs:
      - build-wasm
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Download wasm build
        uses: actions/download-artifact@v2
      - name: Import wasm build
        run: bash .github/deploy-wasm.sh bergamot-translator-worker
      - name: Write version number
        if: startsWith(github.ref, 'refs/tags/v')
        run: bash .github/deploy-tag.sh ${{ github.ref }}
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint:js
        continue-on-error: true
      - name: Build
        run: npm run build
      - name: Sign
        if: startsWith(github.ref, 'refs/tags/v')
        run: npm run sign
        env:
          WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
          WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      - name: Upload extension artifact
        uses: actions/upload-artifact@v2
        with:
          name: bergamot_translations
          path: ${{github.workspace}}/web-ext-artifacts/bergamot_translations*.xpi
      - name: Create Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - name: Upload extension
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./web-ext-artifacts/bergamot_translations.xpi
          asset_name: bergamot_translations.xpi
          asset_content_type: application/zip
